---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.0.4
  amd64: ghcr.io/hassio-addons/base:14.0.4
  armhf: ghcr.io/hassio-addons/base:14.0.4
  armv7: ghcr.io/hassio-addons/base:14.0.4
  i386: ghcr.io/hassio-addons/base:14.0.4
codenotary:
  base_image: notary@home-assistant.io
  signer: lfarkas@lfarkas.org
