---
name: NetBird
version: v0.69.0
slug: netbird
description: Connect your devices into a single secure private WireGuard®-based mesh network.
url: https://github.com/netbirdio/addon-netbird
startup: services
panel_icon: mdi:vpn
init: false
arch:
  - aarch64
  - amd64
host_network: true
host_dbus: true
privileged:
  - SYS_ADMIN
  - SYS_RESOURCE
  - NET_ADMIN
  - NET_RAW
  - BPF
map:
  - homeassistant_config:rw
  - addon_config:rw
options:
  admin_url: ""
  management_url: ""
  setup_key: ""
  hostname: ""
  rosenpass: false
  rosenpass_permissive: false
  env_vars: []
schema:
  admin_url: url?
  management_url: url?
  setup_key: str?
  hostname: match(^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?$)?
  rosenpass: bool
  rosenpass_permissive: bool
  env_vars:
    - name: match(^[A-Z_][A-Z0-9_]*$)
      value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
