name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2

      - name: 🔍 Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@f6f29a7ee3fa0eccadf3620a7b9ee00ab54ec03b # master 2026-04-11

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: find
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2

      - name: 🚀 Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2.21
        with:
          path: "./${{ matrix.path }}"
